stages:
  - build
  - test
  - docker-build

default:
  image: node:24  # version to be compatible with package.json 4.2.2 but its very old
  #tags:
  #  - aws-ec2

.node:build:
  stage: build
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"  # to override cache dir from root to local project dir
  before_script:
    - node -v # get the node version
    - npm -v # get npm version toolkit manager
    #- npm install # installs dependencies looking into the package.json
    - ls -la
    - npm install --package-lock-only  # to generate pakage lock file since npm ci sowrks only if there is apckage lock file
    - npm ci --omit=dev #--only=production # only the installs dependencies not dev dependecies and delete exsisting node modules if exsists
    - ls -la
  script:
    - echo "node env"
    - node index.js
    - ls -la
  cache: # cache the installations based on key file; cache is changed only if the file changes
    key:
      files:
        - package.json 
    paths:
      - .npm/
      - ./package-lock.json
      #- node_modules/  # cannot cacahe node_modules when using npm ci since it deletes on each install need to cache .npm
    policy: pull-push  # default; we can use only push or pull

.node:test_async:
  stage: test
  before_script:
    - npm install --package-lock-only
    - npm ci
  script:
    - echo "Testing the async application"
    - node ./specs/start.js ./specs/async.spec.js

.node:test_db:
  stage: test
  allow_failure: true
  before_script:
    - npm install --package-lock-only
    - npm ci
  services:
    - postgres:9.5.0
  script:
    - echo "Testing the DB"
    - node ./specs/start.js ./specs/db-postgres.spec.js

.dockerize:node:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "building the image"
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_IMAGE"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

.docker:build:  # did not work idgnore
  stage: docker-build
  image: docker:24.0.7-cli
  #needs: []  # to have it run independt of previous jobs
  services:
    - name: docker:24.0.7-dind
      alias: docker
      command:
        - "--storage-driver=overlayfs"  # This configuration ensures that Docker uses the overlayfs storage driver, which is compatible with the containerd-snapshotter.
        - "--feature"  # to enable the containerd iamge store, becuase with the defaul image store it cannot save the cache image
        - "containerd-snapshotter=true"
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - docker info -f '{{ .DriverStatus }}'
  script:
    - echo "docker build with cache..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      docker buildx create --name my-builder --use --driver docker-container --buildkitd-flags '--oci-worker-snapshotter=overlayfs'
      docker buildx inspect --bootstrap
      docker buildx build --push -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
        --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/cache-image:$CI_COMMIT_REF_SLUG \
        --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache-image:$CI_COMMIT_REF_SLUG .

.docker:cache:build:
  stage: docker-build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - docker info
    - docker info -f '{{ .DriverStatus }}'
  variables:
     DOCKER_BUILDKIT: 1 # Enable BuildKit: Use docker buildx with a builder that supports pushing cache
  script: 
    - echo "docekr cache build ..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    #Inside GitLab CI, you should create and use a separate builder instance, because the default one (docker build) often doesn’t support --cache-to=registry
    - docker buildx create --name mybuilder --use
    - docker buildx inspect --bootstrap
    # Print the builder’s info (e.g., supported platforms, cache support, driver)
    # --bootstrap ensures the BuildKit node is started and warmed up
    - |
      docker buildx build \
        --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache:latest \
        --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/cache:latest \
        --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
        --push \
        .
# Configure SAST
include:
  - template: Jobs/SAST.gitlab-ci.yml # SAST (Static Application Security Testing)
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml # Dependency Scanning
  - template: Jobs/Container-Scanning.gitlab-ci.yml # Container Scanning

variables:
  CS_IMAGE: "registry.gitlab.com/sandesh-lab/nodejs:3163ca16"  # For container scanning to work


.get:pakcage:lock:
  stage: build
  script:
    - echo "create lock file"
    - npm install --package-lock-only
  artifacts:
    paths:
      - package-lock.json