stages:
  - build
  - test

node:build:
  stage: build
  image: node:4.2.2  # version to be compatible with package.json
  before_script:
    - node -v # get the node version
    - npm -v # get npm version toolkit manager
    - npm install # installs dependencies looking into the package.json
  script:
    - echo "node env"
    - node index.js
  cache: # cache the installations based on key file
    key:
      files:
        - package.json
    paths:
      - node_modules/
    policy: pull-push  # default; we can use only push or pull