stages:
  - build
  - test

node:build:
  stage: build
  image: node:4.2.2  # version to be compatible with package.json
  before_script:
    - node -v # get the node version
    - npm -v # get npm version toolkit manager
    - ls -la
    - npm install # installs dependencies looking into the package.json
  script:
    - echo "node env"
    - ls -la
    - node index.js
    - ls -la